### ISSUE TITLE
repeated very offten update_coordinator.py:168

### ISSUE THREAD

**Issue by pavel-dpa** [MindrustUK/Heatmiser-for-home-assistant#122]
This error originated from a custom integration.

Logger: custom_components.heatmiserneo
Source: helpers/update_coordinator.py:168
Integration: Heatmiser Neo Climate (documentation)
First occurred: 9:54:46 AM (4 occurrences)
Last logged: 10:07:02 AM

Timeout fetching neostat data

thermostats became unavailable after that.
everything  works fine till last update Home assistant in Jan 2023

**Comment by pavel-dpa** [comment]
This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/heatmiserneo/climate.py:228
Integration: Heatmiser Neo Climate (documentation)
First occurred: 10:24:55 AM (1 occurrences)
Last logged: 10:24:55 AM

Error executing service: <ServiceCall climate.set_temperature (c:01GR614D72DV2J1V38PR33YGH7): temperature=21.5, entity_id=['climate.02childrenroom']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1773, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 613, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/heatmiserneo/climate.py", line 228, in async_set_temperature
    response = await set_target_temperature_task
  File "/usr/local/lib/python3.10/site-packages/neohubapi/neostat.py", line 164, in set_target_temperature
    result = await self._hub.set_target_temperature(temperature, [self])
  File "/usr/local/lib/python3.10/site-packages/neohubapi/neohub.py", line 554, in set_target_temperature
    result = await self._send(message, reply)
  File "/usr/local/lib/python3.10/site-packages/neohubapi/neohub.py", line 99, in _send
    reader, writer = await asyncio.open_connection(self._host, self._port)
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 47, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.11.115', 4242)

**Comment by pavel-dpa** [comment]
Please advice how to fix it :(. due to the fact that this is blocking automation for house climate control depend on thermostats data

**Comment by pavel-dpa** [comment]
One more thing.
Logger: homeassistant.components.homeassistant.triggers.numeric_state
Source: components/homeassistant/triggers/numeric_state.py:185
Integration: Home Assistant Core Integration (documentation, issues)
First occurred: 1:27:41 PM (93 occurrences)
Last logged: 4:13:25 PM

Error in 'Temp_control_winter' trigger: In 'numeric_state' condition: entity climate.01livingroom state '' cannot be processed as a number
Error in 'Temp_control_summer_FIX_REQUIRED' trigger: In 'numeric_state' condition: entity climate.01livingroom state '' cannot be processed as a number
Error in 'Temp_control_spring' trigger: In 'numeric_state' condition: entity climate.01livingroom state '' cannot be processed as a number

**Comment by MindrustUK** [comment]
@pavel-dpa Looks like your Neo-Hub isn't responding

`File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.11.115', 4242)`

Suggest you check the device isn't on a dynamic IP and is correctly responding. If you're seeing this on a frequent basis I'd suggest further investigation of the neohub.

On your second issue please post your automation. It looks like you maybe mixing types.

**Comment by pavel-dpa** [comment]
Hello thanks for respond. my neo-hub has static IP for years and nothing has changed.
There are starting issue with last HA updates 2023.1.
I updated to 2023.2 yesterday - maybe that will help.
regarding second one - that works ok before 2023.1 update also

**Comment by pavel-dpa** [comment]
second case appear when heatmiser thermostats are unavailable

**Comment by pavel-dpa** [comment]
Looks like issue was resolved
