### ISSUE TITLE
' Failed setup, will retry: time data '24:00' does not match format '%H:%M

### ISSUE THREAD

**Issue by funks81** [MindrustUK/Heatmiser-for-home-assistant#163]
I'm getting the following error on the Heatmiser Integration: 

' Failed setup, will retry: time data '24:00' does not match format '%H:%M

Now - this previously was an issue - which I thought had been resolved with something being changed upstream in the Heatmiser API.  However, I've got nothing from any of my thermostats since 0000 this morning.  I've tried restarting HA with no success.  All thermostats online and responding in Heatmiser app.

2024-07-19 14:32:17.132 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration heatmiserneo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-07-19 14:32:21.832 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_COOL was used from heatmiserneo, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.COOL instead, please report it to the author of the 'heatmiserneo' custom integration
2024-07-19 14:32:21.837 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_FAN_ONLY was used from heatmiserneo, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.FAN_ONLY instead, please report it to the author of the 'heatmiserneo' custom integration
2024-07-19 14:32:21.840 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_HEAT was used from heatmiserneo, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please report it to the author of the 'heatmiserneo' custom integration
2024-07-19 14:32:21.842 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_HEAT_COOL was used from heatmiserneo, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT_COOL instead, please report it to the author of the 'heatmiserneo' custom integration
2024-07-19 14:32:22.165 ERROR (MainThread) [custom_components.heatmiserneo] Unexpected error fetching neostat data
File "/config/custom_components/heatmiserneo/__init__.py", line 41, in async_update_data
2024-07-19 14:32:36.212 ERROR (MainThread) [custom_components.heatmiserneo] Unexpected error fetching neostat data
File "/config/custom_components/heatmiserneo/__init__.py", line 41, in async_update_data
2024-07-19 14:32:46.718 ERROR (MainThread) [custom_components.heatmiserneo] Unexpected error fetching neostat data
File "/config/custom_components/heatmiserneo/__init__.py", line 41, in async_update_data
2024-07-19 14:33:07.202 ERROR (MainThread) [custom_components.heatmiserneo] Unexpected error fetching neostat data
File "/config/custom_components/heatmiserneo/__init__.py", line 41, in async_update_data
2024-07-19 14:33:47.981 ERROR (MainThread) [custom_components.heatmiserneo] Unexpected error fetching neostat data
File "/config/custom_components/heatmiserneo/__init__.py", line 41, in async_update_data
2024-07-19 14:35:08.738 ERROR (MainThread) [custom_components.heatmiserneo] Unexpected error fetching neostat data
File "/config/custom_components/heatmiserneo/__init__.py", line 41, in async_update_data
2024-07-19 14:36:29.371 ERROR (MainThread) [custom_components.heatmiserneo] Unexpected error fetching neostat data
File "/config/custom_components/heatmiserneo/__init__.py", line 41, in async_update_data
2024-07-19 14:37:49.997 ERROR (MainThread) [custom_components.heatmiserneo] Unexpected error fetching neostat data
File "/config/custom_components/heatmiserneo/__init__.py", line 41, in async_update_data

**Comment by funks81** [comment]
2024-07-19 16:42:29.900 ERROR (MainThread) [custom_components.heatmiserneo] Unexpected error fetching neostat data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heatmiserneo/__init__.py", line 41, in async_update_data
    _, devices_data = await hub.get_live_data()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/neohubapi/neohub.py", line 449, in get_live_data
    thermostats.append(NeoStat(self, thermostat))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/neohubapi/neostat.py", line 97, in __init__
    _time = datetime.strptime(self.time, "%H:%M")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '24:00' does not match format '%H:%M'

**Comment by funks81** [comment]
Now seems to be resolved - I've not done anything or restarted HA!!!???

**Comment by MindrustUK** [comment]
Going to close this as a random one off. Feel free to re-open if it happens again with any frequency.

**Comment by funks81** [comment]
Re-opening - as have had the same error over the last two nights!!

2024-10-14 00:00:33.428 ERROR (MainThread) [custom_components.heatmiserneo] Unexpected error fetching neostat data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heatmiserneo/__init__.py", line 41, in async_update_data
    _, devices_data = await hub.get_live_data()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/neohubapi/neohub.py", line 449, in get_live_data
    thermostats.append(NeoStat(self, thermostat))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/neohubapi/neostat.py", line 97, in __init__
    _time = datetime.strptime(self.time, "%H:%M")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '24:00' does not match format '%H:%M'
