### ISSUE TITLE
Plugin broken in homeassistant October version - no module named 'neohubapi'

### ISSUE THREAD

**Issue by rogervn** [MindrustUK/Heatmiser-for-home-assistant#174]
Hello, I've just updated my home assistant container to the newest version 2024.10.1 and the plugin now fails to start.

This is the error in the logs:

```
2024-10-05 03:34:12.224 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'heatmiserneo': Unable to import component: No module named 'neohubapi'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/heatmiserneo/__init__.py", line 15, in <module>
    from neohubapi.neohub import NeoHub
ModuleNotFoundError: No module named 'neohubapi'
```

**Comment by MindrustUK** [comment]
Hi @rogervn, I've just patched my main and dev instance and while the main branch is throwing a lot of errors I'll probably need to back port and fix. This was not one of them, I can only assume there was a connection problem fetching the library from pip during boot. Can you restart your home assistant instance and see if this addresses the issue? I'm not sure how you could force retriving the library but it's something else to investigate.

**Comment by rogervn** [comment]
That was actually the deal. After a restart it did work correctly, sorry for the noise.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by MindrustUK** [comment]
Glad it was an easy fix. Closing issue.
