### ISSUE TITLE
Breaking change Home Assistant 0.96

### ISSUE THREAD

**Issue by rosscullen** [MindrustUK/Heatmiser-for-home-assistant#19]
Upgraded Home Assistant to 0.96 today. There's a breaking change in this release due to a heavy revision of their Climate component

Getting the following error:
> Platform not found: climate.heatmiserneo

Would really appreciate if you can have a look into it. Thanks

**Comment by MindrustUK** [comment]
https://developers.home-assistant.io/blog/2019/07/03/climate-cleanup.html

Thanks for the report, I'll take a look at the first chance I get.

**Comment by haakonstorm** [comment]
Just wanted to say thanks a lot for all the work you've put in to this over all this time, and hope you find the time to get thermostats and plugs around the world back up and running in Home Assistant 0.96.x some day :)

**Comment by schford** [comment]
me too just updated and boo hoo :-(

**Comment by MindrustUK** [comment]
Quick and dirty update committed now. Please test and provide feedback. I know there's a lot missing still which I plan to address. I'm just shockingly short of time. Apologies it's taken me so long to address this!

**Comment by haakonstorm** [comment]
Awesome! I'm testing right now. Have two neo-e thermostats and a plug. Feedback in 5!

**Comment by MindrustUK** [comment]
Forgot to migrate the STATE to HVAC mode in my running around. Give that a bash now, HOPEFULLY will work and I'll get round to doing a big clean up one day.

**Comment by haakonstorm** [comment]
- HA 0.97.0
- HASSIO
- RPi3B+ 
- 2 x neo-e thermostats
- 1 x neoplug
- heatmiserneo
- heatmiserneoplug

```
2019-08-09 15:48:36 INFO (SyncWorker_4) [custom_components.heatmiserneo.climate] set_temperature response: {'result': 'temperature was set'} 
```

Everything works 100% again!! 
`<3 <3 <3 `

**Comment by Trouble-51** [comment]
congrats the thermostats are back (all 11). However when i change from off to heat I get the following message:

components/climate/_init_.py (error)      and when i click on the message is says:

Log Details (ERROR)
Fri Aug 09 2019 17:47:20 GMT+0100 (WEST)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 128, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 210, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 334, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 356, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 416, in async_set_hvac_mode
    await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 412, in set_hvac_mode
    raise NotImplementedError()
NotImplementedError


and states shows:

hvac_modes: heat,off
current_temperature: 24.9
min_temp: 7
max_temp: 35
temperature: 27
current_humidity: 0
hvac_action: heat
friendly_name: Study Jos
supported_features: 1
icon: mdi:fire
idle: mdi:sleep
away: mdi:leaf

**Comment by rosscullen** [comment]
Much appreciated @MindrustUK 
Will give it a whirl and see how goes. Really appreciate you taking the time to update, considering your up the walls! Sincere thanks! R :-)

**Comment by MindrustUK** [comment]
Closing as per fixes in Pull request.
