### ISSUE TITLE
Refresh/Sync Task Error with v3.0.0-beta.13

### ISSUE THREAD

**Issue by hirenshah** [MindrustUK/Heatmiser-for-home-assistant#234]
Not sure if this is related to your code or known issue. 

Running HA 2024.12.5.  

```
Logger: homeassistant
Source: components/climate/__init__.py:337
First occurred: 21:00:57 (2 occurrences)
Last logged: 21:01:27

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 267, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 478, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 558, in _handle_coordinator_update
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1087, in __async_calculate_state
    if state_attributes := self.state_attributes:
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 337, in __getattribute__
    return super().__getattribute__(name)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 545, in state_attributes
    hass, self.current_temperature, temperature_unit, precision
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 337, in __getattribute__
    return super().__getattribute__(name)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/config/custom_components/heatmiserneo/climate.py", line 296, in current_temperature
    ) and self._unit_of_measurement == "C":
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 337, in __getattribute__
    return super().__getattribute__(name)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
AttributeError: 'NeoStatEntity' object has no attribute '_unit_of_measurement'. Did you mean: 'unit_of_measurement'?
```

**Comment by ocrease** [comment]
@hirenshah thanks for reporting this. I think I can see the problem, but it should only happen if the thermostat is reporting a temperature under -50 or above 70. There is a comment saying it could happen if the hub disconnects.

If its still happening, could you download [diagnostics](https://mindrustuk.github.io/Heatmiser-for-home-assistant/faqs.html) and upload it here? It would help to see what is being reported by the hub.

**Comment by hirenshah** [comment]
Attached :)
[config_entry-heatmiserneo-01JBDG2ZV9FHH78ZPYAFYGDWRG.json](https://github.com/user-attachments/files/18271327/config_entry-heatmiserneo-01JBDG2ZV9FHH78ZPYAFYGDWRG.json)

**Comment by ocrease** [comment]
@hirenshah thanks. The only device showing a strange temperature is a NeoPlug, but that shouldn'e have been set up as a climate entity in the first place. Did you recently upgrade to the pre-release branch? There was also a bug in a recent pre-release version where offline devices where getting the wrong device type and strange things could happen. This has been fixed now. When you go to the "Plug" device information page, what does it show? I would expect something like this:

![image](https://github.com/user-attachments/assets/2c478959-56b5-47b0-ab6e-337da7db9bf6)

It might be worth deleting the hub and re-adding it to clean out any invalid entities. 

![image](https://github.com/user-attachments/assets/405c3746-65f3-4ff8-a86f-104ef6307e6c)

**Comment by hirenshah** [comment]
![image](https://github.com/user-attachments/assets/75e40a39-2479-4f58-8f84-cc5b6c2a7a9a)

Will try removing and readding the hub :)

**Comment by hirenshah** [comment]
Just spotted this in the logs:

`2024-12-30 14:30:54.062 ERROR (MainThread) [custom_components.heatmiserneo.climate] Error: Climate entity 'Bedrooms' has an invalid current_temperature value: 127.255 degrees Centigrade, Hub lost connection?
`

**Comment by ocrease** [comment]
@hirenshah ok I think it has nothing to do with the plug. That error message is expected if your thermostats report a temperature that is outside a realistic range. How long does it happen for? If you look at that thermostat on the heatmiser app, does it also show some crazy temperatures?

I see that you have several wireless room temperature sensors and several of your thermostats are set up in "mix" mode where the temperature is the average of the thermostat temperature and the average of any connected wireless sensors on that zone. On the diagnostics file you uploaded earlier I can see that several of the wireless sensors are being reported as offline and I suspect this is causing your issue.

The best thing you can do is work out why your wireless sensors are not connecting reliably, probably interference on the zigbee network used by Heatmiser (or those sensors are too far away).

**Comment by ocrease** [comment]
Hi @hirenshah, do you need any more help with this?

**Comment by hirenshah** [comment]
Apologies for not getting back to you.  I've not seen the errors since sorting the connection issue with Wireless Temperature Sensors.  Thanks :)

**Comment by ocrease** [comment]
That's great to hear
